### ISSUE TITLE
Support for GHA's setup-python pre-release version specifiers

### ISSUE THREAD

**Issue by hynek** [wntrblm/nox#685]
### How would this feature be useful?

Currently, nox supports the setup-python notation for stable Python versions perfectly.

You can write something like:

```yaml
jobs:
  tests:
    name: nox on ${{ matrix.runs-on }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        python-version: ["pypy3.8", "3.8", "3.9", "3.10"]
        runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - python -m pip install --upgrade wheel virtualenv nox

      - run: nox --python ${{ matrix.python-version }}
```

And it just works. It even works with `"3.11.0-beta - 3.11"` – although by accident.

But it doesn't work at all with the modern `~3.12.0-0` (that matches both prereleases as well as eventual stable versions), which means that one is forced to keep kind of a "lookup table" like in [Towncrier](https://github.com/twisted/towncrier/blob/ffcc117225504d7275a9662be421d1494c33e907/.github/workflows/ci.yml#L61-L75) which is a bit of a bummer.

### Describe the solution you'd like

My proposal now is that nox should accept all `python-version` syntaxes.

Another great option would be to be able to say `nox -p current` or something like that, that will use the Python version that is running nox. That would essentially implement tox-gh-actions.

### Describe alternatives you've considered

Well, the table thing I've used in Towncrier that is also necessary for

**Comment by mayeut** [comment]
@hynek, you can use:
```yaml
jobs:
  tests:
    name: nox on ${{ matrix.runs-on }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        python-version: ["pypy3.8", "3.8", "3.9", "3.10", "3.12"]
        runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - python -m pip install --upgrade wheel virtualenv nox

      - run: nox --python ${{ matrix.python-version }}
```
