### ISSUE TITLE
Cannot install package from Azure Artifacts

### ISSUE THREAD

**Issue by thecesrom** [wntrblm/nox#709]
### Current Behavior

Locally `nox` does install packages from Azure Artifacts, but when running `nox` on Azure Pipelines, the task "hangs" as it is expecting me to provide credentials.

### Expected Behavior

The package should install without asking for credentials.

### Steps To Reproduce

noxfile.py

```python
"""Nox config."""
import nox

BASE_PYTHON = "3.10"
PIP_INDEXES = {
    "PIP_INDEX_URL": "https://company.pkgs.visualstudio.com/Project/_packaging/Company_Project/pypi/simple/",
    "PIP_EXTRA_INDEX_URL": "https://pypi.org/simple/",
}

nox.options.reuse_existing_virtualenvs = True
nox.options.sessions = ["typecheck"]
nox.options.stop_on_first_error = True


@nox.session(python=BASE_PYTHON, venv_params=["--system-site-packages"])
def test(session: nox.Session) -> None:
    """Run type check on code base."""
    session.install(private-package, env=PIP_INDEXES)

```

azure-pipelines.yaml

```yaml
      - task: PipAuthenticate@1
        inputs:
          artifactFeeds: "Project/Company_Project"

      - script: |
          nox
        displayName: Run tests
```

Output:

```sh
nox > Running session test
nox > Creating virtual environment (virtualenv) using python3.10 in .nox/test
nox > python -m pip install private-package
nox > Command python -m pip install private-package failed with exit code 2:
Looking in indexes: https://company.pkgs.visualstudio.com/Project/_packaging/Company_Project/pypi/simple/, https://pypi.org/simple/
User for company.pkgs.visualstudio.com:
```

### Environment

```Markdown
- OS: Ubuntu 20.04
- Python: 3.10.11
- Nox: 2023.4.22
```

### Anything else?

It works in `tox`.
