### ISSUE TITLE
[GHA] nox uses Python 3.11 for sessions with no Python version specified, despite `python-versions` being set to `3.13`

### ISSUE THREAD

**Issue by felixfontein** [wntrblm/nox#943]
### Current Behavior

If I use the GHA with
```
      - name: Setup nox
        uses: wntrblm/nox@2025.02.09
        with:
          python-versions: "3.13"
```
and then run a session that has no specific Python version, like
```
@nox.session
def lint(session: nox.Session):
    ...
```
then nox runs the session with Python 3.11 instead of 3.13.

Example: https://github.com/ansible-community/antsibull-docs-parser/actions/runs/13891427869/job/38863981140
1. "Setup nox" shows that `python-versions` is `3.13`;
2. "Set up nox environments" shows that a venv is created with Python version 3.11.

### Expected Behavior

I would expect that the session runs with Python 3.13.

### Steps To Reproduce

See above.

### Environment

```Markdown
- OS: Ubuntu 24.04
- Python: 3.11/3.12/3.13 (the action first installs 3.12, then installs 3.13 and 3.11)
- Nox: latest
```
